import type { Metadata } from 'next';
import { ThemeProvider } from '@/components/Providers/ThemeProvider/theme-provider';
import { ResetCSS } from '@/styles';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider>
          <ResetCSS />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
